<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="annotations" nsURI="http://www2.compute.dtu.dk/annotations"
    nsPrefix="anno">
  <eClassifiers xsi:type="ecore:EClass" name="EnabledTransition" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTransition" eType="#//SelectArc"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTransition" eType="#//SelectArc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectArc" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outArcs" upperBound="-1"
        eType="#//EnabledTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inArcs" upperBound="-1"
        eType="#//EnabledTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marking" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation ../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//TextualAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceSelectionAnnotation" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlaceMarkingAnnotation" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation ../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//TextualAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mode">
    <eLiterals name="enabled"/>
    <eLiterals name="fired" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionActivationAnnotation" eSuperTypes="../org.pnml.tools.epnk.annotations/model/NetAnnotations.ecore#//ObjectAnnotation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//Mode"/>
  </eClassifiers>
</ecore:EPackage>
